### ISSUE TITLE
Segementation fault

### ISSUE THREAD

**Issue by shreyakupadhyay** [marcpare/stitch#1]
I am getting Segmentation fault when I am running stitch.py. The problem is in this line
"kp = detector.detect(image_gs)", 39 line in stitch.py. I have searched it on stackoverflow and those solutions doesn't seem to be working. Can I get any help on this? It will be very helpful. Thank you.

**Comment by marcpare** [comment]
I'm not actively maintaining this repository. It's possible the installation that worked a few years ago no longer does. Feel free to submit a PR with a fix.
